FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-smbus \
    i2c-tools \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir paho-mqtt numpy smbus2

WORKDIR /app
COPY hardware/ ./hardware/

CMD ["python", "-u", "hardware/main.py"]
